# toml
[versions]
kotlin = "2.3.0-RC3"
graalvm = "0.11.3"
spring-boot = "4.0.0"
spring-dependency-management = "1.1.7"

spotless = "8.1.0"

[libraries]
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin.jvm", name = "org.jetbrains.kotlin.jvm.gradle.plugin", version.ref = "kotlin" }

spring-boot-starter-actuator = { group = "org.springframework.boot", name = "spring-boot-starter-actuator", version.ref = "spring-boot" }
spring-boot-starter-hateoas  = { group = "org.springframework.boot", name = "spring-boot-starter-hateoas",  version.ref = "spring-boot" }
spring-boot-starter-webmvc   = { group = "org.springframework.boot", name = "spring-boot-starter-webmvc",   version.ref = "spring-boot" }
spring-boot-devtools         = { group = "org.springframework.boot", name = "spring-boot-devtools",         version.ref = "spring-boot" }
spring-boot-configuration-processor = { group = "org.springframework.boot", name = "spring-boot-configuration-processor", version.ref = "spring-boot" }

spring-boot-starter-test     = { group = "org.springframework.boot", name = "spring-boot-starter-test", version.ref = "spring-boot" }

spotless-gradlePlugin = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version.ref = "spotless" }


[bundles]

[plugins]
graalvm = { id = "org.graalvm.buildtools.native", version.ref = "graalvm" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }